# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

services:
  redis-vector-db:
    image: redis/redis-stack:7.2.0-v9
    container_name: redis-vector-db
    ports:
      - "${REDIS_PORT1:-6379}:6379"
      - "${REDIS_PORT2:-8001}:8001"
    environment:
      HTTPS_PROXY: ${http_proxy}
      HTTP_PROXY: ${https_proxy}
    healthcheck:
      test: ["CMD-SHELL", "sleep 10 && exit 0"]
      interval: 1s
      timeout: 15s
      retries: 1
